### ISSUE TITLE
教科書に関する質問

### ISSUE THREAD

**Issue by satoshi-inaba** [j-otsuki/comput-phys-book#1]
教科書を読み、とても勉強になりました。
ありがとうございます。

いくつか質問がありますので、ここに記述させてください。
１）p.43 (2.34)式の右辺第２項の符号はプラスではないでしょうか？
２）p.78 本文上から２行目の　y_1 = l_11/b_1 は　y_1 = b_1/l_11 ではないでしょうか？
３）p.82 phaiの次元は[V]、epsilonの次元は[C/V m]ではないでしょうか？
４）p.85 57,59行目の　id_xはid_yではないでしょうか？
５）p.107 (4.17)式の S^2 = 3/4 I でIが抜けてないでしょうか？
６）p.115 本文中央あたりの　さて、以下の文章で　全スピンS=3/2、S=1/2の2種類で
　　縮退度はそれぞれ４重、４重ではないでしょうか？

お忙しいところ誠に申し訳ございません。
宜しくお願いいたします。

**Comment by j-otsuki** [comment]
質問の投稿第1号ありがとうございます！

簡単に答えられるところから回答します。
今日中にはすべて回答します。

>２）p.78 本文上から２行目の　y_1 = l_11/b_1 は　y_1 = b_1/l_11 ではないでしょうか？

その通りです。誤植のご指摘ありがとうございます。

>４）p.85 57,59行目の　id_xはid_yではないでしょうか？

これはid_xのままで正しいです。
x方向を表す単位行列とy方向を表す差分行列をクロネッカー積で組み合わせて、2次元空間の差分表現を作っています。

これが正しいことは、111行目で
```
nx, ny = 51, 101
```
のように、x方向とy方向で異なるサイズをとってみるとわかります。
id_xだとエラーが出ないですが、id_yだとエラーが出てしまいます。

>５）p.107 (4.17)式の S^2 = 3/4 I でIが抜けてないでしょうか？

たしかに単位行列が必要です。
単位行列は省略する文献が多いですが、この教科書では省略せずに書いた方がいいですね。

>６）p.115 本文中央あたりの　さて、以下の文章で　全スピンS=3/2、S=1/2の2種類で縮退度はそれぞれ４重、４重ではないでしょうか？

該当の文章はスピンの合成則の話をしていて、3つのS=1/2の合成から、S=3/2が1つとS=1/2が2つ出ると言っています。
縮退度は4重、2重、2重です。

2つのS=1/2をまとめて「4重縮退」と呼ばないのは、その縮退はモデルに依るからです。
本で扱っている３サイトハイゼンベルグモデルの場合には、2つのS=1/2が縮退しているので、全スピン以外にも何か別の保存量があるはず、という話の流れになっています。

**Comment by j-otsuki** [comment]
>３）p.82 phaiの次元は[V]、epsilonの次元は[C/V m]ではないでしょうか？

その通りです。誤植の指摘ありがとうございます。

**Comment by j-otsuki** [comment]
>１）p.43 (2.34)式の右辺第２項の符号はプラスではないでしょうか？

その通りです。ご指摘ありがとうございます。

プラスでないと、(2.30)式と合いませんね。

**Comment by j-otsuki** [comment]
>>５）p.107 (4.17)式の S^2 = 3/4 I でIが抜けてないでしょうか？
>
>たしかに単位行列が必要です。
>単位行列は省略する文献が多いですが、この教科書では省略せずに書いた方がいいですね。

すいません、訂正です。
(4.17)式は演算子の関係式（ハットは演算子を表す）なので、右辺に単位行列のIは必要ありませんでした。

以下の2つの式はどちらも正しいです。

- 演算子の関係式
  ![image](https://github.com/j-otsuki/comput-phys-book/assets/22098787/5ecffd20-28ef-4254-a7cd-321c759ae0f6)

- 表現行列の関係式
  ![image](https://github.com/j-otsuki/comput-phys-book/assets/22098787/9e601fd1-c606-4438-b272-6a39fafc74e8)

教科書は1つ目の式です。

**Comment by j-otsuki** [comment]
正誤表をHPにアップロードしました。
https://j-otsuki.github.io/comput-phys-book/#正誤表

コメントありがとうございました。

**Comment by satoshi-inaba** [comment]
早速のお返事ありがとうございました。

2024年1月10日(水) 15:14 Junya Otsuki ***@***.***>:
