### ISSUE TITLE
誤植のご報告

### ISSUE THREAD

**Issue by kumonamu** [j-otsuki/comput-phys-book#2]
些細な点で恐縮ですが、
p.18 式 (2.10), (2.11), (2.13), (2.14)：「t」→「t_n」
ではないでしょうか？
お手すきの際にご確認いただければ幸いです。
よろしくお願いいたします。

**Comment by j-otsuki** [comment]
ご指摘ありがとうございます。

おっしゃるとおりです。
4式とも、正しくはt_nです。

**Comment by j-otsuki** [comment]
正誤表に反映させたので、このissueは閉じます。
ご指摘ありがとうございました。

**Comment by kumonamu** [comment]
ご対応いただき、ありがとうございました。
正誤表は[GitHubリポジトリ](https://github.com/j-otsuki/comput-phys-book/blob/main/corrections/corrections.pdf)の方ではなく、[出版社のページ](https://www.morikita.co.jp/books/mid/017081)の方に反映されるのですね。

**Comment by j-otsuki** [comment]
はい。
前はリポジトリにも正誤表を掲載していましたが、出版社の方が正式なものなので、そちらへのリンクに変えました。
